#!/usr/bin/env bash
set -Eeuo pipefail

repo_root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
sources_file="$repo_root/infra/images.sources.env"
lock_file="$repo_root/infra/images.lock.env"

[[ -f $sources_file ]] || { echo "Missing $sources_file" >&2; exit 1; }
command -v docker >/dev/null 2>&1 || { echo "docker is required" >&2; exit 1; }

set -a
# shellcheck disable=SC1090
source "$sources_file"
set +a

source_vars=(
  SEARXNG_IMAGE_SOURCE
  VALKEY_IMAGE_SOURCE
  FIRECRAWL_IMAGE_SOURCE
  PLAYWRIGHT_IMAGE_SOURCE
  NUQ_POSTGRES_IMAGE_SOURCE
  REDIS_IMAGE_SOURCE
  RABBITMQ_IMAGE_SOURCE
  SANDBOX_BASE_IMAGE_SOURCE
)

[[ ${FIRECRAWL_REQUIRED_RELEASE:-} == v2.11.0 ]] || {
  echo "Review and update the tested Firecrawl release before changing v2.11.0." >&2
  exit 1
}
[[ ${FIRECRAWL_REQUIRED_COMMIT:-} == ef12eb36b2f3 ]] || {
  echo "The reviewed Firecrawl v2.11.0 commit must remain ef12eb36b2f3." >&2
  exit 1
}
[[ $FIRECRAWL_IMAGE_SOURCE == *":sha-$FIRECRAWL_REQUIRED_COMMIT-linux-arm64" ]] || {
  echo "Firecrawl API image must use the v2.11.0 ARM64 commit tag." >&2
  exit 1
}

tmp=$(mktemp "$repo_root/infra/.images.lock.XXXXXX")
trap 'rm -f -- "$tmp"' EXIT
printf '# Generated by scripts/lock-images.sh; do not edit.\n' > "$tmp"

for source_var in "${source_vars[@]}"; do
  source_ref=${!source_var:-}
  [[ -n $source_ref ]] || { echo "$source_var is empty" >&2; exit 1; }
  echo "Pulling linux/arm64 $source_ref"
  docker pull --platform linux/arm64 "$source_ref"
  image_arch=$(docker image inspect --format '{{.Architecture}}' "$source_ref")
  [[ $image_arch == arm64 ]] || { echo "$source_ref resolved to $image_arch, not arm64" >&2; exit 1; }

  repo=${source_ref%:*}
  digest_sha=$(docker image inspect --format '{{json .RepoDigests}}' "$source_ref" \
    | jq -r 'map(split("@")[-1]) | map(select(startswith("sha256:"))) | first // empty')
  [[ $digest_sha == sha256:* ]] || { echo "No immutable repo digest found for $source_ref" >&2; exit 1; }
  digest="${repo}@${digest_sha}"

  lock_var=${source_var%_SOURCE}
  printf '%s=%s\n' "$lock_var" "$digest" >> "$tmp"
done

chmod 0644 "$tmp"
mv -f -- "$tmp" "$lock_file"
trap - EXIT
echo "Locked images written to $lock_file"
